nb_players: 2
timer_start: 20
timer_jump: 5
timer_max: 60

items:
  restart:
    slot: 3
    material: INK_SACK
    amount: 1
    data: 1

blocks:
  world:
  x:
    min_x:
    max_x:
  z:
    min_z:
    max_z:
  y:

lobbyspawn:
arenas:
